### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by kreativmonkey** [kreativmonkey/Git-Workshop#1]
- [ ] Einteilung der Abschnitte in Lektionen #3 
- [ ] Ausgestaltung einer Einführenden Präsentation
- [ ] Erstellung eines Sheet Cheats als Hands-On
- [ ] Ablauf an einer Testgruppe *g*
